name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2.2-alpine' # Specify your Ruby version

      - name: Install dependencies
        run: bundle install

      - name: Lint and test
        run: |
          bundle exec rubocop
          bundle exec rspec

      - name: Build Docker image
        # run: docker build -t yourdockerusername/first_ruby_project_repo .
        run: docker build -t rubyproject

      - name: Push Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # username: ayushitomar2711@gmail.com
          # password: DAayushi@123
        run: docker push aayushitomar123/first_ruby_project_repo

